# CA1 - Data Visualisation and Communication

## Cover Page

Lecturer Name: Taufique Ahmed 
### Barbara Souza 2023059
### GitHub Link
https://github.com/BarbSouza/data-visualisation.git
### Video Link
https://drive.google.com/drive/folders/19yAy5wb7vKj4OV-kTpZ81bX17kZqhXc9?usp=drive_link

## Imports and the reading the dataset

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

dataset =  pd.read_excel("all_data_M_2023.xlsx")

## Dataset Description Field

In [2]:
dataset_description = pd.read_excel("all_data_M_2023.xlsx", sheet_name="Field Descriptions")

In [3]:
pd.set_option("display.max_colwidth", None)
dataset_description

,May 2023 OEWS Estimates,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN
1,Occupational Employment and Wage Statistics (OEWS) Survey,NaN,NaN
2,"Bureau of Labor Statistics, Department of Labor",NaN,NaN
3,website: www.bls.gov/oes,NaN,NaN
4,email: oewsinfo@bls.gov,NaN,NaN
5,NaN,NaN,NaN
6,Not all fields are available for every type of estimate,NaN,NaN
7,NaN,NaN,NaN
8,Field,Field Description,NaN
9,area,"U.S. (99), state FIPS code, Metropolitan Statistical Area (MSA) or New England City and Town Area (NECTA) code, or OEWS-specific nonmetropolitan area code",NaN
10,area_title,Area name,NaN
11,area_type,Area type: 1= U.S.; 2= State; 3= U.S. Territory; 4= Metropolitan Statistical Area (MSA) or New England City and Town Area (NECTA); 6= Nonmetropolitan Area,NaN
12,prim_state,"The primary state for the given area. ""US"" is used for the national estimates.",NaN
13,naics,North American Industry Classification System (NAICS) code for the given industry,NaN
14,naics_title,North American Industry Classification System (NAICS) title for the given industry,NaN
15,i_group,"Industry level. Indicates cross-industry or NAICS sector, 3-digit, 4-digit, 5-digit, or 6-digit industry. For industries that OEWS no longer publishes at the 4-digit NAICS level, the “4-digit” designation indicates the most detailed industry breakdown available: either a standard NAICS 3-digit industry or an OEWS-specific combination of 4-digit industries. Industries that OEWS has aggregated to the 3-digit NAICS level (for example, NAICS 327000) will appear twice, once with the “3-digit” and once with the “4-digit” designation.",NaN
16,own_code,"Ownership type: 1= Federal Government; 2= State Government; 3= Local Government; 123= Federal, State, and Local Government; 235=Private, State, and Local Government; 35 = Private and Local Government; 5= Private; 57=Private, Local Government Gambling Establishments (Sector 71), and Local Government Casino Hotels (Sector 72); 58= Private plus State and Local Government Hospitals; 59= Private and Postal Service; 1235= Federal, State, and Local Government and Private Sector",NaN
17,occ_code,The 6-digit Standard Occupational Classification (SOC) code or OEWS-specific code for the occupation,NaN
18,occ_title,SOC title or OEWS-specific title for the occupation,NaN
19,o_group,"SOC occupation level. For most occupations, this field indicates the standard SOC major, minor, broad, and detailed levels, in addition to all-occupations totals. For occupations that OEWS no longer publishes at the SOC detailed level, the “detailed” designation indicates the most detailed data available: either a standard SOC broad occupation or an OEWS-specific combination of detailed occupations. Occupations that OEWS has aggregated to the SOC broad occupation level will appear in the file twice, once with the “broad” and once with the “detailed” designation.",.
20,tot_emp,Estimated total employment rounded to the nearest 10 (excludes self-employed).,NaN
21,emp_prse,"Percent relative standard error (PRSE) for the employment estimate. PRSE is a measure of sampling error, expressed as a percentage of the corresponding estimate. Sampling error occurs when values for a population are estimated from a sample survey of the population, rather than calculated from data for all members of the population. Estimates with lower PRSEs are typically more precise in the presence of sampling error.",NaN
22,jobs_1000,"The number of jobs (employment) in the given occupation per 1,000 jobs in the given area. Only available for the state and MSA estimates; otherwise, this column is blank.",.
23,loc quotient,"The location quotient represents the ratio of an occupation’s share of employment in a given area to that occupation’s share of employment in the U.S. as a whole. For example, an occupation that makes up 10 percent of employment in a specific metropolitan area compared with 2 percent of U.S. employment would have a location quotient of 5 for the area in question. Only available for the state, metropolitan area, and nonmetropolitan area estimates; otherwise, this column is blank.",NaN
24,pct_total,"Percent of industry employment in the given occupation. Percents may not sum to 100 because the totals may include data for occupations that could not be published separately. Only available for the national industry estimates; otherwise, this column is blank.",.
25,pct_rpt,"Percent of establishments reporting the given occupation for the cell. Only available for the national industry estimates; otherwise, this column is blank.",NaN
26,h_mean,Mean hourly wage,NaN
27,a_mean,Mean annual wage,NaN
28,mean_prse,"Percent relative standard error (PRSE) for the mean wage estimate. PRSE is a measure of sampling error, expressed as a percentage of the corresponding estimate. Sampling error occurs when values for a population are estimated from a sample survey of the population, rather than calculated from data for all members of the population. Estimates with lower PRSEs are typically more precise in the presence of sampling error.",NaN
29,h_pct10,Hourly 10th percentile wage,NaN
30,h_pct25,Hourly 25th percentile wage,NaN
31,h_median,Hourly median wage (or the 50th percentile),NaN
32,h_pct75,Hourly 75th percentile wage,NaN
33,h_pct90,Hourly 90th percentile wage,NaN
34,a_pct10,Annual 10th percentile wage,NaN
35,a_pct25,Annual 25th percentile wage,NaN
36,a_median,Annual median wage (or the 50th percentile),NaN
37,a_pct75,Annual 75th percentile wage,NaN
38,a_pct90,Annual 90th percentile wage,NaN
39,annual,"Contains ""TRUE"" if only annual wages are released. The OEWS program releases only annual wages for some occupations that typically work fewer than 2,080 hours per year, but are paid on an annual basis, such as teachers, pilots, and athletes.",.
40,hourly,"Contains ""TRUE"" if only hourly wages are released. The OEWS program releases only hourly wages for some occupations that typically work fewer than 2,080 hours per year and are paid on an hourly basis, such as actors, dancers, and musicians and singers.",.
41,NaN,NaN,NaN
42,Notes:,NaN,NaN
43,* = indicates that a wage estimate is not available,NaN,NaN
44,** = indicates that an employment estimate is not available,NaN,NaN
45,"# = indicates a wage equal to or greater than $115.00 per hour or $239,200 per year",NaN,NaN
46,~ =indicates that the percent of establishments reporting the occupation is less than 0.5%,NaN,NaN

## Dataset info

In [4]:
dataset.head(10)

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,23.11,37.01,58.4,29050,35660,48060,76980,121470,NaN,NaN
1,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,56.19,81.29,111.36,54550,78330,116880,169090,231620,NaN,NaN
2,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,49.74,79.57,#,46400,66170,103460,165500,#,NaN,NaN
3,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
4,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,99.37,#,#,80000,130840,206680,#,#,NaN,NaN
5,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1020,General and Operations Managers,...,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
6,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,48.69,77.06,111.59,46340,65180,101280,160290,232110,NaN,NaN
7,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1030,Legislators,...,*,*,*,21010,28810,47290,82200,129510,True,NaN
8,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-1031,Legislators,...,*,*,*,21010,28810,47290,82200,129510,True,NaN
9,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,11-2000,"Advertising, Marketing, Promotions, Public Relations, and Sales Managers",...,67.23,96.15,#,69170,99180,139850,199990,#,NaN,NaN

In [5]:
dataset.shape

(413327, 32)

rows (occupation) x columns (information)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413327 entries, 0 to 413326
Data columns (total 32 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AREA          413327 non-null  int64
 1   AREA_TITLE    413327 non-null  object
 2   AREA_TYPE     413327 non-null  int64
 3   PRIM_STATE    413327 non-null  object
 4   NAICS         413327 non-null  object
 5   NAICS_TITLE   413327 non-null  object
 6   I_GROUP       413327 non-null  object
 7   OWN_CODE      413327 non-null  int64
 8   OCC_CODE      413327 non-null  object
 9   OCC_TITLE     413327 non-null  object
 10  O_GROUP       413327 non-null  object
 11  TOT_EMP       413327 non-null  object
 12  EMP_PRSE      413327 non-null  object
 13  JOBS_1000     235826 non-null  object
 14  LOC_QUOTIENT  235826 non-null  object
 15  PCT_TOTAL     170470 non-null  object
 16  PCT_RPT       170470 non-null  object
 17  H_MEAN        413327 non-null  object
 18  A_MEAN        413327 non-null  object
 19  MEAN_PRSE     413327 non-null  object
 20  H_PCT10       413327 non-null  object
 21  H_PCT25       413327 non-null  object
 22  H_MEDIAN      413327 non-null  object
 23  H_PCT75       413327 non-null  object
 24  H_PCT90       413327 non-null  object
 25  A_PCT10       413327 non-null  object
 26  A_PCT25       413327 non-null  object
 27  A_MEDIAN      413327 non-null  object
 28  A_PCT75       413327 non-null  object
 29  A_PCT90       413327 non-null  object
 30  ANNUAL        16497 non-null   object
 31  HOURLY        755 non-null     object
dtypes: int64(3), object(29)
memory usage: 100.9+ MB

Only AREA, AREA_TYPE and OWN_CODE are numeric
That should be fixed so in the charts all information can be counted and visualised, the reason they are text is because a few cells contain symbols.

In [7]:
dataset.isnull().sum()

AREA                 0
AREA_TITLE           0
AREA_TYPE            0
PRIM_STATE           0
NAICS                0
NAICS_TITLE          0
I_GROUP              0
OWN_CODE             0
OCC_CODE             0
OCC_TITLE            0
O_GROUP              0
TOT_EMP              0
EMP_PRSE             0
JOBS_1000       177501
LOC_QUOTIENT    177501
PCT_TOTAL       242857
PCT_RPT         242857
H_MEAN               0
A_MEAN               0
MEAN_PRSE            0
H_PCT10              0
H_PCT25              0
H_MEDIAN             0
H_PCT75              0
H_PCT90              0
A_PCT10              0
A_PCT25              0
A_MEDIAN             0
A_PCT75              0
A_PCT90              0
ANNUAL          396830
HOURLY          412572
dtype: int64

Jobs_1000 and LOC_QuOITIENT exists only for state and metropolitan area rows
pct_Total and PCT_RPT are empty because they only exist for national industry rows
ANNUAL and Hourly are almost entirely empty becaus they are only filled for unusual occupations.

In [8]:
dataset.describe()

               AREA      AREA_TYPE       OWN_CODE
count  4.133270e+05  413327.000000  413327.000000
mean   3.784693e+05       2.766826     717.279984
std    1.135906e+06       1.780825     601.852382
min    1.000000e+00       1.000000       1.000000
25%    9.900000e+01       1.000000       5.000000
50%    9.900000e+01       2.000000    1235.000000
75%    3.710000e+04       4.000000    1235.000000
max    7.800001e+06       6.000000    1235.000000

Only shows the code columns so the avarages are not meaninful

In [9]:
dataset.value_counts("AREA_TYPE")

AREA_TYPE
1    177501
4    149591
6     48559
2     36643
3      1033
Name: count, dtype: int64

rows per kind of area
- 1 - Whole US
- 2 - states
- 3 - territories
- 4 - metropolitan
- 6 - non-metropolitan

In [10]:
dataset.value_counts("I_GROUP")

I_GROUP
cross-industry               237229
4-digit                       83350
3-digit                       39097
sector                        16376
5-digit                       15518
4-digit, ownership             9856
cross-industry, ownership      5628
3-digit, ownership             4561
6-digit                        1712
Name: count, dtype: int64

rows per industry level

In [11]:
dataset.value_counts("O_GROUP")

O_GROUP
detailed    306185
broad        62131
minor        23374
major        20601
total         1036
Name: count, dtype: int64

rows per occupation level

In [12]:
dataset.value_counts("OWN_CODE")

OWN_CODE
1235    237229
5       144246
235       8465
2         6419
3         6076
57        3689
123       3538
1         1878
58         960
59         827
Name: count, dtype: int64

rows per ownership type

In [13]:
dataset.value_counts("TOT_EMP")

TOT_EMP
40           19325
50           16872
60           14450
70           12537
**           11598
             ...
151853870        1
130039030        1
22068580         1
21814850         1
18533450         1
Name: count, Length: 12271, dtype: int64

how often each employment figure appears

In [14]:
dataset.value_counts("A_MEDIAN")

A_MEDIAN
*         5083
#         2391
41600      618
31200      584
52000      572
          ...
237780       1
236650       1
236920       1
238120       1
238160       1
Name: count, Length: 16664, dtype: int64

Change the * to no information and # 239,200 per year

Need to seperate the rows so the same ocuppation don't get count more than once

## Cleaning

In [15]:
clean = dataset.copy()

In [26]:
for col in ["A_MEDIAN", "TOT_EMP", "A_MEAN", "A_PCT10", "A_PCT25", "A_PCT75", "A_PCT90"]:
    clean[col] = clean[col].replace("#", 239200)
    clean[col] = pd.to_numeric(clean[col], errors="coerce")

In [27]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413327 entries, 0 to 413326
Data columns (total 32 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AREA          413327 non-null  int64
 1   AREA_TITLE    413327 non-null  object
 2   AREA_TYPE     413327 non-null  int64
 3   PRIM_STATE    413327 non-null  object
 4   NAICS         413327 non-null  object
 5   NAICS_TITLE   413327 non-null  object
 6   I_GROUP       413327 non-null  object
 7   OWN_CODE      413327 non-null  int64
 8   OCC_CODE      413327 non-null  object
 9   OCC_TITLE     413327 non-null  object
 10  O_GROUP       413327 non-null  object
 11  TOT_EMP       401729 non-null  float64
 12  EMP_PRSE      413327 non-null  object
 13  JOBS_1000     235826 non-null  object
 14  LOC_QUOTIENT  235826 non-null  object
 15  PCT_TOTAL     170470 non-null  object
 16  PCT_RPT       170470 non-null  object
 17  H_MEAN        413327 non-null  object
 18  A_MEAN        408244 non-null  float64
 19  MEAN_PRSE     413327 non-null  object
 20  H_PCT10       413327 non-null  object
 21  H_PCT25       413327 non-null  object
 22  H_MEDIAN      413327 non-null  object
 23  H_PCT75       413327 non-null  object
 24  H_PCT90       413327 non-null  object
 25  A_PCT10       408244 non-null  float64
 26  A_PCT25       408244 non-null  float64
 27  A_MEDIAN      408244 non-null  float64
 28  A_PCT75       408244 non-null  float64
 29  A_PCT90       408244 non-null  float64
 30  ANNUAL        16497 non-null   object
 31  HOURLY        755 non-null     object
dtypes: float64(7), int64(3), object(22)
memory usage: 100.9+ MB

In [28]:
clean["TOT_EMP"].isnull().sum()

np.int64(11598)

In [29]:
clean["A_MEDIAN"].isnull().sum()

np.int64(5083)

In [30]:
clean.describe()

,AREA,AREA_TYPE,OWN_CODE,TOT_EMP,A_MEAN,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90
count,4.133270e+05,413327.000000,413327.000000,4.017290e+05,4.082440e+05,408244.000000,408244.000000,408244.000000,408244.000000,408244.000000
mean,3.784693e+05,2.766826,717.279984,1.275895e+04,6.810923e+04,42905.108367,51510.702203,63460.996610,78346.608425,94751.161242
std,1.135906e+06,1.780825,601.852382,3.608032e+05,3.866052e+04,20248.761249,26227.641535,33782.605405,41967.481657,50381.550438
min,1.000000e+00,1.000000,1.000000,3.000000e+01,1.675000e+04,15080.000000,15080.000000,15080.000000,16670.000000,16950.000000
25%,9.900000e+01,1.000000,5.000000,1.000000e+02,4.321000e+04,30350.000000,35110.000000,40160.000000,48110.000000,58010.000000
50%,9.900000e+01,2.000000,1235.000000,3.200000e+02,5.734000e+04,37440.000000,44630.000000,53430.000000,65530.000000,79530.000000
75%,3.710000e+04,4.000000,1235.000000,1.530000e+03,8.143000e+04,49250.000000,60890.000000,76970.000000,96990.000000,119500.000000
max,7.800001e+06,6.000000,1235.000000,1.518539e+08,1.805790e+06,239200.000000,239200.000000,239200.000000,239200.000000,239200.000000

In [43]:
national=clean.loc[(clean['AREA_TYPE'] == 1) & (clean["I_GROUP"] == "cross-industry") & (clean["O_GROUP"] == "detailed") & (clean["OCC_CODE"].str.startswith("15-"))]
national.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
135,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,15-1211,Computer Systems Analysts,...,49.9,63.74,79.66,63230.0,80380.0,103800.0,132580.0,165700.0,NaN,NaN
136,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,15-1212,Information Security Analysts,...,57.87,73.82,87.68,69210.0,90050.0,120360.0,153550.0,182370.0,NaN,NaN
138,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,15-1221,Computer and Information Research Scientists,...,69.75,89.02,112.07,81450.0,109990.0,145080.0,185160.0,233110.0,NaN,NaN
140,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,15-1231,Computer Network Support Specialists,...,34.39,44.5,58.61,45660.0,54700.0,71530.0,92570.0,121920.0,NaN,NaN
141,99,U.S.,1,US,000000,Cross-industry,cross-industry,1235,15-1232,Computer User Support Specialists,...,28.48,36.52,46.65,37690.0,46550.0,59240.0,75950.0,97020.0,NaN,NaN

In [44]:
national.shape

(21, 32)

In [46]:
state=clean.loc[(clean['AREA_TYPE'] == 2) & (clean["O_GROUP"] == "detailed") & (clean["OCC_CODE"].str.startswith("15-"))]
state.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
181042,1,Alabama,2,AL,000000,Cross-industry,cross-industry,1235,15-1211,Computer Systems Analysts,...,49.31,63.6,80.35,63980.0,79490.0,102560.0,132280.0,167130.0,NaN,NaN
181043,2,Alaska,2,AK,000000,Cross-industry,cross-industry,1235,15-1211,Computer Systems Analysts,...,41.69,52.63,61.11,50620.0,61180.0,86720.0,109460.0,127110.0,NaN,NaN
181044,4,Arizona,2,AZ,000000,Cross-industry,cross-industry,1235,15-1211,Computer Systems Analysts,...,48.21,61.57,69.07,49170.0,69100.0,100280.0,128070.0,143660.0,NaN,NaN
181045,5,Arkansas,2,AR,000000,Cross-industry,cross-industry,1235,15-1211,Computer Systems Analysts,...,37.12,47.44,61.55,54040.0,60900.0,77210.0,98670.0,128020.0,NaN,NaN
181046,6,California,2,CA,000000,Cross-industry,cross-industry,1235,15-1211,Computer Systems Analysts,...,59.79,75.56,89.16,75520.0,96750.0,124370.0,157170.0,185460.0,NaN,NaN

In [47]:
state.shape

(973, 32)

In [49]:
industry=clean.loc[(clean['AREA_TYPE'] == 1) & (clean["I_GROUP"] == "sector") & (clean["O_GROUP"] == "detailed") & (clean["OCC_CODE"].str.startswith("15-"))]
industry.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
2850,99,U.S.,1,US,11,"Agriculture, Forestry, Fishing and Hunting",sector,5,15-1211,Computer Systems Analysts,...,45.41,62.55,86.27,65570.0,72210.0,94450.0,130110.0,179440.0,NaN,NaN
2852,99,U.S.,1,US,11,"Agriculture, Forestry, Fishing and Hunting",sector,5,15-1232,Computer User Support Specialists,...,33.96,39.48,49.19,46140.0,51110.0,70640.0,82120.0,102320.0,NaN,NaN
2854,99,U.S.,1,US,11,"Agriculture, Forestry, Fishing and Hunting",sector,5,15-1244,Network and Computer Systems Administrators,...,42.36,52.08,65.02,51970.0,73790.0,88120.0,108320.0,135250.0,NaN,NaN
2856,99,U.S.,1,US,11,"Agriculture, Forestry, Fishing and Hunting",sector,5,15-1252,Software Developers,...,60.81,67.92,77.97,67600.0,102340.0,126490.0,141280.0,162170.0,NaN,NaN
2858,99,U.S.,1,US,11,"Agriculture, Forestry, Fishing and Hunting",sector,5,15-1299,"Computer Occupations, All Other",...,41.57,60.91,63.5,55610.0,58540.0,86470.0,126690.0,132080.0,NaN,NaN

In [50]:
industry.shape

(357, 32)

## Visualisation 1
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 2
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 3
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 4
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Visualisation 5
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.

## Challenge
1. What is the **objective** of the visualisation? (eg investigation, comparison etc)
2. **Why that visualisation type was chosen**? (categorical, numerical, relationships).  
3. **What you learned** about AI employment from the visualisation.